version: '3'
services:
  automation-interface:
    image: mis-automation-test:latest
    container_name: mis-automation-test
    restart: always
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - "/opt/automation-test/templates:/var/local/templates"
      # - "/var/local/templates:/opt/automation-test/templates"
#      - "/var/local/logs:/opt/interAuto/resources/logger"
#      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 3G